### ISSUE TITLE
Override spinach-rerun.txt file location

### ISSUE THREAD

**Issue by sargissargsyan** [javierav/spinach-rerun-reporter#1]
are there any way to override spinach-rerun.txt file location?

**Comment by javierav** [comment]
Currently no, but I'm open to ideas :smile:

**Comment by sargissargsyan** [comment]
Did you use this gem to rerun test on Teamcity?

**Comment by javierav** [comment]
No, but I updated the code with some improvements, can you check it?

**Comment by sargissargsyan** [comment]
Nice! I like the dynamic variables 👍  Is it already released? can I get it with "gem install spinach-rerun-reporter"?

**Comment by javierav** [comment]
Hi! I just release the version 1.0.0 of this gem with all the new changes. Sorry for the silence time. I close this issue.
