### ISSUE TITLE
Release last changes

### ISSUE THREAD

**Issue by Jack12816** [javierav/spinach-rerun-reporter#2]
Hey @javierav! Thanks for this great gem! 

Could you please release the latest master (6135aeec0ebcdf7e05fcf25c150d31a7121c9333)? This would be really helpful. I would love to get rid of:

```
gem 'spinach-rerun-reporter',
    git: 'https://github.com/javierav/spinach-rerun-reporter.git',
    ref: '6135aeec0ebcdf7e05fcf25c150d31a7121c9333'   
```

Thank you very much! :)

**Comment by Jack12816** [comment]
Ping?

**Comment by javierav** [comment]
Hi @Jack12816, I'm sorry for not answering at this time. I promise to work on this in the coming days 👌

**Comment by Jack12816** [comment]
Thanks mate! :)

**Comment by javierav** [comment]
Hi! I just release the version 1.0.0 of this gem with all the new changes. Sorry for the silence time. I close this issue.
