### ISSUE TITLE
The tasks directory is missing on the released gem

### ISSUE THREAD

**Issue by Jack12816** [javierav/spinach-rerun-reporter#4]
Hey @javierav, it looks like the `tasks/` directory is not bundled with the gem relase.
So it is not possible to run `$ rake spinach:rerun` and https://github.com/javierav/spinach-rerun-reporter/blob/master/lib/spinach-rerun-reporter/rails.rb#L4 fails.

```bash
$ ls -lisa /usr/lib/ruby/gems/2.5.0/gems/spinach-rerun-reporter-1.0.0/

drwxr-xr-x 4 root root 4,0K 2018-10-01, 13:09:02  lib
-rw-r--r-- 1 root root 1,1K 2018-10-01, 13:09:02  LICENSE
-rw-r--r-- 1 root root 2,1K 2018-10-01, 13:09:02  README.md
-rw-r--r-- 1 root root  781 2018-10-01, 13:09:02  spinach-rerun-reporter.gemspec
```

Could you add the tasks directory to https://github.com/javierav/spinach-rerun-reporter/blob/master/spinach-rerun-reporter.gemspec#L22 ?

**Comment by javierav** [comment]
Good catch! Merged and released new gem version! Apologyze for the error!

**Comment by Jack12816** [comment]
Thanks mate!
